services:
  - type: web
    name: skilllink
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT skilllink.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: skilllink.settings
      - key: CLOUDINARY_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: skilllink-redis
          property: connectionString
    region: singapore

  - type: redis
    name: skilllink-redis
    region: singapore
    ipAllowList: [] # only allow internal connections
    plan: free # Use free plan for Redis if available, or starter
